[[redirects]]
  from = "/chencho/*"
  to = "https://chencho-27.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://chencho-27.netlify.app/:splat"
  status = 200