[[redirects]]
  from = "/chencho/*"
  to = "https://chencho-27.netlify.app/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/blog/*"
  to = "https://blog.kairoz.dev/:splat"
  status = 200
  force = true